### ISSUE TITLE
Possibility to display Link as well

### ISSUE THREAD

**Issue by arjitc** [kodosexe/F1Hub#3]
First of all - Thank you!

I see 2 options currently when playing a Live Stream,

- Play with MPV
- Copy to Clipboard

Could a 3rd option be added called "Display Link" which can be copied easier from CLI/Console into VLC ?

**Comment by kodosexe** [comment]
Hey,
Thanks for the suggestion.

I'm not sure what you mean by this. Once implemented (because I haven't yet), the Copy to Clipboard feature will directly copy the link, so all you need to do is paste it into VLC, etc.

I'm not sure what benefits there would be to display the link directly, but there may be use cases I'm not thinking of right now, so I'm open to examples.

The copy to clipboard feature will be implemented before the first race for sure (I may even be able to do it tomorrow, if all works well), and an option to display the link would be no problem at all, but it seems kind of redundant to me.

**Comment by arjitc** [comment]
Probably the oddest use-case really, but I run most of my python/linux stuff under a VM (which has no GUI etc) and connect to it via Putty/Kitty, the copy-to-clipboard function seems to not work across those layers (so far).

**Comment by ius** [comment]
> I'm not sure what benefits there would be to display the link directly, but there may be use cases I'm not thinking of right now, so I'm open to examples.

I usually play media such as F1 by launching `mpv` on my Wayland/X-less Linux machine. Ideally I'd run F1Hub on the same box, but *copy to clipboard* obviously doesn't work in that case, nor does launching mpv (but that's a different issue).

Now if launching `mpv` directly would work I wouldn't need the URL in the first place, but being able to display the stream URL seems like a neat fallback option to me.

**Comment by kodosexe** [comment]
That is an odd use case :D

I'll find a way to elegantly implement it in the future. For now, you can add a print statement to the getM3U8 file, followed by a couple second time.sleep to give you time to copy it

**Comment by kodosexe** [comment]
Hey, I just added the feature.
Please test it before I close the issue.
Thanks!

**Comment by arjitc** [comment]
Hi,
Does not work :( The menu remains stuck/frozen when "Display Link" is picked.

I did a git pull & re-tested as well just before replying here now

**Comment by kodosexe** [comment]
I just made a new commit that should add a "Playable Link" message before the link.
A freeze of 10 seconds is planned, but it should now at least display something.

Also, how are you accessing it? (In terms of over the live Menu, id Menu or season menu) They are all coded in separately as of now, so that would help narrow it down. Do the other ways work?

**Comment by arjitc** [comment]
> I just made a new commit that should add a "Playable Link" message before the link.
> A freeze of 10 seconds is planned, but it should now at least display something.

Thank you! I'll give it a try later today 👍 

So far I added a tempfix by writing the contents of the `url` variable to a file just before returning it (in getM3U8Stream.py).

> Also, how are you accessing it? (In terms of over the live Menu, id Menu or season menu) They are all coded in separately as of now, so that would help narrow it down. Do the other ways work?

Accessing it via the Live Menu :)

**Comment by kodosexe** [comment]
Hey, any update on this?

**Comment by arjitc** [comment]
Sorry forgot to check further today! :(
