### ISSUE TITLE
MPV play not working

### ISSUE THREAD

**Issue by nherring07** [kodosexe/F1Hub#8]
Not sure if it's an error on my end, but for some reason when I try to play with the MPV I get this error:

> Darwin
> Could not start Windows stream

**Comment by kodosexe** [comment]
Hey, thank's for submitting.

It seems like you're on an old version - "Darwin" is the command line environment for MacOS. In older versions, it used to say "starting Windows" nonetheless. This has been fixed in 4df98b7a38fd0847acd0e84c949aa3f9bdf6b5f2, along with the actual command that plays the stream.

Please make sure you're on the latest version, then try again. Please let me know if the error still persists then.
If the output doesn't change, it may be left out from the latest version. If that's the case, please let me know and I'll try to push an update before the race starts.

Thanks!
Kodos

**Comment by nherring07** [comment]
Thanks for the quick response and solution. That fixed the problem.

Cheers,
N

**Comment by kodosexe** [comment]
Glad it worked. Enjoy the race!
